import type { Metadata } from "next";
import { Poppins, Kantumruy_Pro } from "next/font/google";
import { notFound } from "next/navigation";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import ProgressBarProvider from "@/components/providers/ProgressBarProvider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "E-Menu Dashboard",
  description: "Generated by create next app",
};

interface Props {
  children: any;
  params: any;
}

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const kantumruy = Kantumruy_Pro({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-kantumruy",
});

export default async function RootLayout({ children, params }: Props) {
  let messages;
  try {
    messages = (await import(`../../locales/${params.locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={params.locale}>
      <body
        className={cn(
          poppins.className,
          kantumruy.className,
          "fixed h-screen w-screen bg-background antialiased"
        )}
      >
        <ProgressBarProvider>
          <NextIntlClientProvider locale={params.locale} messages={messages}>
            {children}
            <Toaster
              richColors
              duration={10000}
              position="top-center"
              theme="light"
            />
          </NextIntlClientProvider>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
